In [1]:
import pandas as pd
import numpy as np

In [2]:
match=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries.csv')

In [14]:
match.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [3]:
total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [4]:
total_score_df=total_score_df[total_score_df['inning']==1]

In [5]:
total_score_df

      match_id  inning  total_runs
0            1       1         207
2            2       1         184
4            3       1         183
6            4       1         163
8            5       1         157
...        ...     ...         ...
1518     11347       1         143
1520     11412       1         136
1522     11413       1         171
1524     11414       1         155
1526     11415       1         152

[756 rows x 3 columns]

In [6]:
match_df=match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')

In [7]:
teams=[
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

In [8]:
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [9]:
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [10]:
match_df=match_df[match_df['team1'].isin(teams)]
match_df=match_df[match_df['team2'].isin(teams)]

In [11]:
match_df=match_df[match_df['dl_applied']==0]

In [12]:
match_df=match_df[['match_id','city','winner','total_runs']]

In [13]:
delivery_df=match_df.merge(delivery,on='match_id')

In [14]:
delivery_df=delivery_df[delivery_df['inning']==2]

In [29]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
126,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,1,PA Patel,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,2,PA Patel,...,0,0,0,0,1,0,1,NaN,NaN,NaN
128,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,3,JC Buttler,...,0,0,0,0,0,0,0,NaN,NaN,NaN
129,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,4,JC Buttler,...,0,0,0,0,0,0,0,NaN,NaN,NaN
130,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,5,JC Buttler,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53640,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,0,0,1,0,1,NaN,NaN,NaN
53641,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,0,0,2,0,2,NaN,NaN,NaN
53642,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
53643,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,0,0,2,0,2,NaN,NaN,NaN
53644,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [15]:
delivery_df['current_score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [32]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score
126,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,1,PA Patel,...,0,0,0,0,0,0,NaN,NaN,NaN,0
127,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,2,PA Patel,...,0,0,0,1,0,1,NaN,NaN,NaN,1
128,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,3,JC Buttler,...,0,0,0,0,0,0,NaN,NaN,NaN,1
129,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,4,JC Buttler,...,0,0,0,0,0,0,NaN,NaN,NaN,1
130,10,Mumbai,Mumbai Indians,158,2,Mumbai Indians,Sunrisers Hyderabad,1,5,JC Buttler,...,0,0,0,4,0,4,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53640,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,0,1,0,1,NaN,NaN,NaN,152
53641,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,0,2,0,2,NaN,NaN,NaN,154
53642,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,0,1,0,1,SR Watson,run out,KH Pandya,155
53643,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,0,2,0,2,NaN,NaN,NaN,157
53644,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,0,SN Thakur,lbw,NaN,157

In [16]:
delivery_df['runs_left']=delivery_df['total_runs_x']-delivery_df['current_score']

In [17]:
delivery_df['balls_left']=120-(delivery_df['over']*6 + delivery_df['ball'])

In [18]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x== "0" else "1")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
wickets=delivery_df.groupby('match_id')['player_dismissed'].cumsum().values
delivery_df['wickets']=10-wickets
delivery_df.head(5)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,0,1,0,NaN,NaN,1,206,113,10
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,112,10
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,111,10
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,0,2,0,NaN,NaN,3,204,110,10
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,0,4,0,NaN,NaN,7,200,109,10

In [19]:
delivery_df.tail(5)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
112351,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,1,0,1,0,NaN,NaN,152,0,-2,5
112352,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,2,0,2,0,NaN,NaN,154,-2,-3,5
112353,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,0,1,1,run out,KH Pandya,155,-3,-4,4
112354,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,2,0,2,0,NaN,NaN,157,-5,-5,4
112355,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,1,lbw,NaN,157,-5,-6,3

In [20]:
delivery_df['crr']=(delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

In [21]:
delivery_df['rrr']=(delivery_df['runs_left']*6)/delivery_df['balls_left']

In [22]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [23]:
delivery_df['result']=delivery_df.apply(result,axis=1)

In [24]:
delivery_df=delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr','result']]

In [25]:
delivery_df=delivery_df.sample(delivery_df.shape[0])

In [26]:
delivery_df.dropna(inplace=True)

In [27]:
delivery_df.isnull().sum()

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets         0
total_runs_x    0
crr             0
rrr             0
result          0
dtype: int64

In [28]:
delivery_df=delivery_df[delivery_df['balls_left']!=0]

In [29]:
x=delivery_df.iloc[:,:-1]
y=delivery_df.iloc[:,-1]

In [54]:
x

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr
31304,Chennai Super Kings,Mumbai Indians,Kolkata,100,62,4,148,4.965517,9.677419
49270,Sunrisers Hyderabad,Delhi Capitals,Delhi,57,65,8,134,8.400000,5.261538
2935,Delhi Daredevils,Mumbai Indians,Mumbai,158,100,8,162,1.200000,9.480000
23845,Deccan Chargers,Chennai Super Kings,Chennai,119,81,9,160,6.307692,8.814815
31033,Mumbai Indians,Rajasthan Royals,Kolkata,131,86,10,165,6.000000,9.139535
...,...,...,...,...,...,...,...,...,...
28428,Sunrisers Hyderabad,Delhi Daredevils,Hyderabad,39,78,9,80,5.857143,3.000000
34990,Delhi Daredevils,Rajasthan Royals,Ahmedabad,86,9,2,201,6.216216,57.333333
39329,Delhi Daredevils,Rajasthan Royals,Mumbai,131,72,8,189,7.250000,10.916667
47568,Chennai Super Kings,Sunrisers Hyderabad,Mumbai,89,48,6,148,4.916667,11.125000
1599,Delhi Daredevils,Rajasthan Royals,Delhi,57,64,9,129,7.714286,5.343750

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=2)

In [58]:
y_train

14326    0
24847    1
41781    1
38863    0
38908    0
        ..
44182    0
48255    1
17507    1
32765    1
27230    1
Name: result, Length: 16989, dtype: int64

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf=ColumnTransformer([
    ('trf',OneHotEncoder(drop='first',sparse_output=False),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [33]:
pipe=Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [34]:
pipe.fit(x_train,y_train)

c:\Users\shish\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [35]:
y_pred=pipe.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.8136758938214063

In [37]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))